### ISSUE TITLE
Feature: Add ability to run transform/map function on every function that returns a doc/docs.

### ISSUE THREAD

**Issue by j** [aheckmann/mquery#100]
I'd like to use mquery, but want to transform every document to a class without having to do it manually every time (such as https://github.com/j/type-mongo-mapper).

**Comment by Fonger** [comment]
This feature is only available on `mongodb@3.1.0` and up.
mquery use `mongodb@2.2` so it's not working. Try to upgrade 3.1.0 by yourself and see if it works.

**Comment by j** [comment]
@Fonger I believe they removed the map functionality that I implemented in the driver already since they want to put it on the (de)serialization BSON layer.  I'll close this for now though.
