### ISSUE TITLE
Several problems about shell and node-mongodb-native compatibility

### ISSUE THREAD

**Issue by Fonger** [aheckmann/mquery#109]
I would like to discuss some problems I found so far

1. `mquery` calls `findAndModify` internally to support `findOneAndUpdate` and `findOneAndRemove`.
  [`findAndModify` has been marked as **deprecated** since `node-mongodb-native` 2.2](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#findAndModify). `mquery` has [mongodb dependency 2.2+](https://github.com/aheckmann/mquery/blob/45c4bd104613da47828df13d4aec12c324525c53/package.json#L28) so we should update it even though the latest 3.1 still supports findAndModify.

2. Returning modified document after update: `new` vs `returnOriginal` vs `returnNewDocument`

   - [**new** is valid for `findAndModify` in both `mongo shell`](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/) and [`node-mongodb-native`](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findAndModify).
   - [**returnOriginal** is only valid for `findOneAndUpdate` in `node-mongodb-native` ](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findOneAndUpdate)
   - [**returnNewDocument** is only valid for `findOneAndUpdate` in `mongo shell`](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/)

   - [**new** is the only valid option in `mquery().findOneAndUpdate()`](https://github.com/aheckmann/mquery/blob/45c4bd104613da47828df13d4aec12c324525c53/lib/mquery.js#L2609).
     **This is inconsistent with either `mongo shell` or `node-mongodb-native`** because `mquery` use `findAndModify` to support `findOneAndUpdate`. If we update mquery to call `findOneAndUpdate` directly from `node-mongodb-native`,  `new` is not valid anymore and we should use `returnOriginal` instead. This is a breaking change.

     This is so annoying. I don't know why mongodb uses different names for different environments. The worst thing is that `returnOriginal` is opposite of `returnNewDocument`. We have to decide if we want to support all of these syntax, or make a breaking changes? Maybe we should support all of these syntax in different calls and throw an error if there is a conflict in options?

   - [If **new** is not defined in `findAndModify` options, `mquery` defaults to `true`](https://github.com/aheckmann/mquery/blob/45c4bd104613da47828df13d4aec12c324525c53/lib/mquery.js#L2681) so it will return new modified data. Although we want to get modified document in most cases, **this behavior is not the same with either `mongo shell` or `node-mongodb-native` that defaults to `false`**. They return old document by default.

3. In mongo shell and `node-mongodb-native`, there is no `findOneAndRemove`. Only `findOneAndDelete` method exists. Should we add `findOneAndDelete` as alias to avoid confusion?

4. Add `findOneAndReplace` #104 I don't know how to use `findAndModify` to implement findOneAndReplace. Maybe just call `findOneAndReplace` from `node-mongodb-native`  like point 1. suggests?

**Comment by aheckmann** [comment]
> In mongo shell and node-mongodb-native, there is no findOneAndRemove.
Only findOneAndDelete.

A bit of history, mquery/mongoose was ahead of the curve on fluid syntax.
Overall, if mquery is now significantly outdated, I'm in favor of a semver
major release to realign with MongoDB.

> Should we add the findOneAndDelete alias to avoid confusion?

Sounds wise.

**Comment by vkarpov15** [comment]
1) Mongoose has a flag to work around this, we should add a similar one to mquery
2) We should add support for returnOriginal
3) findOneAndDelete should be separate, not just an alias, because findOneAndDelete should not use findAndModify
4) findOneAndReplace should not use findAndModify
