### ISSUE TITLE
"collection.count is deprecated"

### ISSUE THREAD

**Issue by bcmux** [aheckmann/mquery#111]
It looks like **count** is being deprecated, and replaced with **countDocuments**. Users may receive the deprecation warning if this is called with mquery.

**Error:**
`(node:9893) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead`

**Problem:**
node_modules/mquery/lib/collection/node.js:48
```
NodeCollection.prototype.count = function(match, options, cb) {
   this.collection.count(match, options, cb);
};
```

**Fix:**
```
NodeCollection.prototype.countDocuments = function(match, options, cb) {
    this.collection.countDocuments(match, options, cb);
};
```

**Comment by vkarpov15** [comment]
We may add a `countDocuments()` function in the future, but for now we're leaving that function in Mongoose.
