### ISSUE TITLE
Feature Request: Subclass Promise

### ISSUE THREAD

**Issue by Ayplow** [aheckmann/mquery#114]
To allow directly awaiting a query, make the `Query` class subclass `Promise`.

For reference, this works in the babel compiler - 

```js
class P extends Promise {
  constructor(fn) {
    if (typeof fn === "function") // Necessary for creating child promises in `.then`
      return super(fn)
    super(res => res())
  }
}
(async () => {
  await new P
  console.log('Done')
})()
```

**Comment by vkarpov15** [comment]
Not going to happen any time soon because queries are "cold" by default - a query doesn't start executing until you call `exec()`. Queries are already thenable, so there isn't much benefit to making a query a fully fledged promise.
