### ISSUE TITLE
server deploy broken

### ISSUE THREAD

**Issue by dcsan** [aheckmann/mquery#117]
I'm deploying code that seems to rely on this module, but it breaks the runtime!

on the server I see this:

> Cannot find module '/mnt/ext250/web-apps/cbg.rik.ai/node_modules/mquery/node_modules/debug/src/index.js

and indeed that `debug/src` dir doesn't exist

```
$ ls node_modules/mquery/node_modules/debug/
CHANGELOG.md  karma.conf.js  LICENSE  Makefile  node.js  package.json  README.md
```

on my local dev machine it DOES exist.

is there something that could cause this to install or not?

**Comment by dcsan** [comment]
I guess its a dep of mongoose

```
cofbot@0.0.2 /Users/dc/dev/exiteer/xbot/server
└─┬ mongoose@5.10.0
  └── mquery@3.2.2
```

**Comment by dcsan** [comment]
is there any reason you would install with the `debug/src` files on a mac for example but without them in production?

**Comment by dcsan** [comment]
oops my bad I had an ignore on all `src` for my deploy process.
not sure why the `npm i` on the server didn't reinstall everything... 

i guess linking to directly the `src` directory for TJ's `debug` is ok? and not a dist version?

anyway I'll close this issue shortly, just leave it here for your checking a day or so.

**Comment by vkarpov15** [comment]
We don’t require() in debug’s src directory directly, but debug does. The debug module doesn’t have a dist directory.
