### ISSUE TITLE
Chained query incorrectly merges conditions

### ISSUE THREAD

**Issue by 09setht** [aheckmann/mquery#38]
The following query should return no results because an id cannot satisfy both conditions:
<code>model.find({id:'a'}).find({id:{$ne:'a'}})</code>
However, only the last condition is processed, resulting in the condition:
<code>{id:{$ne:'a'}}</code>
Instead of overwriting the first condition, the two conditions should be combined with $and so that the condition is:
<code>$and:[{id'a'},{id:{$ne:'a'}}]</code>

The following edit in Query.prototype merge is an example of what may work (tested)
```
Query.prototype.merge = function (source) {
  if (!source)
    return this;
...

//plain object
//NEW CODE
	if (Object.keys(source).length) {
		if (Object.keys(this._conditions).length) {
			if (this._conditions.$and && this._conditions.$and.length)
				this._conditions.$and.push(source)
			else
				this._conditions = {$and: [this._conditions, source]};
		}
		else
			this._conditions = source;
	}
//END NEW CODE

  return this;
}
```

**Comment by aheckmann** [comment]
This module cannot know if the developer intends to merge as you propose or intends to overwrite (the current behavior). In this case use `.and({id:{$ne:'a'}})`.
