### ISSUE TITLE
How to perform nested queries?

### ISSUE THREAD

**Issue by jhsware** [aheckmann/mquery#62]
If I need to do write a query like this, where the AND is nested under an OR. How do I accomplish this? Does mquery support it? Or do I need to use regular syntax? In other words, can I pass a query as a parameter to OR in this case:

```
{
        _id: objId,
        $or: [{ 
            $and: [
                {
                    mayView: {
                        $all: ['owner']
                    }
                }, 
                {
                    owners: {
                        $all: [userId]
                    }
                }
            ]
        }, {
            mayView: {
                $all: [userRole]
            }
        }]
}
```

**Comment by vkarpov15** [comment]
This is a moot point, the $and is redundant, as $and usually is. Should be supported in theory though - are you getting an error of some sort?

**Comment by jhsware** [comment]
True, in this case :) What I wanted to do was something like this:
    
    .or([
        and([
            expr1,
            expr2
        ],
        expr3
    ])

But I am not sure if it was supported in any way since it isn't mentioned in the docs. But I implemented that part using Mongodb Query syntax instead, which is working.

**Comment by vkarpov15** [comment]
Is there an actual error somewhere? The should be supported, it is valid mongodb query syntax, although still redundant. Generally [`$and` is only useful if you want an 'and' of 'ors'](http://docs.mongodb.org/manual/reference/operator/query/and/#and-queries-with-multiple-expressions-specifying-the-same-operator). If no error, please close.
