### ISSUE TITLE
Order of multiple sort fields is not preserved

### ISSUE THREAD

**Issue by skleeschulte** [aheckmann/mquery#67]
mquery does not preserve the order of multiple sort fields. Sort fields and sort order are stored in object properties (see https://github.com/aheckmann/mquery/blob/master/lib/mquery.js#L1234). An array should be used instead. In addition it should be possible to pass an array to `sort`, e.g. `sort([{ field1: 1 }, { field2: -1 }])`.

MongoDB native driver also accepts an array, see docs (http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#sort) and code (http://mongodb.github.io/node-mongodb-native/2.0/api/lib_cursor.js.html#line512).

**Comment by skleeschulte** [comment]
Or better, support the same format as the MongoDB dirver: `[['field1', 1], ['field2', -1]]`

**Comment by vkarpov15** [comment]
I do agree about being able to support an array. However, in most cases the "de-facto standard" where v8 object keys retain their insertion order is sufficient, unless you're looking to run mquery on an old browser.

**Comment by skleeschulte** [comment]
There is another exception: Numeric field names, which are possible in MongoDB (see e.g. here https://jira.mongodb.org/browse/SERVER-3229).The order of numeric ("integer") property names is not preserved in V8 (see https://code.google.com/p/v8/issues/detail?id=164). Thus, configuring the sort as `{ 2: -1, 1: 1 }` won't work as it will be changed to `{ 1: 1, 2: -1 }`.

For now, the same issue exists in MongoDB's native node.js driver, but will hopefully change - see https://jira.mongodb.org/browse/NODE-578

**Comment by vkarpov15** [comment]
Ah good old ECMAScript spec section 6.1.7 rears its ugly head again. I'll put together a fix for this tomorrow.

**Comment by skleeschulte** [comment]
:)

**Comment by vkarpov15** [comment]
By tomorrow I meant "I'm gonna forget about this for a while" :)
