### ISSUE TITLE
Outdated bluebird

### ISSUE THREAD

**Issue by matskiv** [aheckmann/mquery#73]
Hey, have you considered updating bluebird to newer 2.x version? I would be glad if it was at least [v2.9.31](https://github.com/petkaantonov/bluebird/releases/tag/v2.9.31) because it fixes this [bug](https://github.com/petkaantonov/bluebird/issues/661).
Thanks.

**Comment by aheckmann-pebble** [comment]
Could you open a PR? Let's see how CI does.

**Comment by aheckmann** [comment]
closed via 25ad624
