### ISSUE TITLE
Guard against RangeErrors

### ISSUE THREAD

**Issue by adambuczynski** [aheckmann/mquery#78]
I got a `RangeError: Maximum call stack size exceeded` from within mquery. I am not 100% sure yet how this happened and with what data, but it was after trying to do an update operation on a Mongoose model.

Maybe mquery could implement a guard against this though?

Relevant stack trace portion:

```

node_modules/mongoose/lib/model.js in Function.update at line 2059
node_modules/mongoose/lib/query.js in Query.update at line 2192
node_modules/mquery/lib/mquery.js in Query.update at line 2042
node_modules/mquery/lib/mquery.js in Query.merge at line 1655
node_modules/mquery/lib/utils.js in Object.merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
node_modules/mquery/lib/utils.js in merge at line 161
```

And this goes on:

![image](https://cloud.githubusercontent.com/assets/490562/18223838/c7a64e72-7217-11e6-9d3f-6a4ab8c94b55.png)

**Comment by aheckmann** [comment]
Sounds like a very deep object is being merged. Can you post a gist of the objects/queries being used?

**Comment by adambuczynski** [comment]
That's the thing, I don't think it was, but there might have been recursion in the object. I'll try to analyse it and provide more information if I can reproduce it.

**Comment by adambuczynski** [comment]
At this stage we are unable to reproduce this because we don't know exactly what data we used. There were some problems with our migration data but they have since been fixed.

My guess still remain though, I think there might have been some recursion going on in the data, as we don't have overly large objects (at most 3-4 levels deep).

**Comment by aheckmann** [comment]
Thank you. I'm going to close this for now. Please open a new ticket if you can reproduce.
