### ISSUE TITLE
Vulnerability issue in debug package

### ISSUE THREAD

**Issue by sulaiman-alwie** [aheckmann/mquery#86]
Vulnerability is in ms package used by debug. Please refer to https://snyk.io/vuln/npm:ms:20151024.

debug package [v2.6.7](https://github.com/visionmedia/debug/releases/tag/2.6.7) has addressed this issue.

**Comment by vkarpov15** [comment]
Bumped the version :point_up: thanks for reporting

**Comment by popomore** [comment]
@vkarpov15 hi, have you release a new version for this security issue? I see the version 2.3.0 is released in March.

**Comment by vkarpov15** [comment]
Released 2.3.1 and mongoose 4.10.2 to address this :+1:
