### ISSUE TITLE
Aggregate method

### ISSUE THREAD

**Issue by notgne2** [aheckmann/mquery#95]
Is there any plans to add an `aggregate()` method any time soon, or do you have any pointers for how to add such a thing myself?

**Comment by vkarpov15** [comment]
@notgne2 not planned because aggregate is very different from `find()`, `update()`, etc. If we wanted to put this in mquery, we'd have to do something similar to mongoose's aggregation pipeline builder

**Comment by Banandana** [comment]
https://github.com/hexafluoride/mquery
