### ISSUE TITLE
npm install mquery - not working!

### ISSUE THREAD

**Issue by yogsagot** [aheckmann/mquery#98]
There is some issue with sliced module.

yogsagot@debian:~/Documents/tarotlogexpert/app$ npm install mquery
npm ERR! path /home/yogsagot/Documents/tarotlogexpert/app/node_modules/.staging/sliced-76f37b1b
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/yogsagot/Documents/tarotlogexpert/app/node_modules/.staging/sliced-76f37b1b' -> '/home/yogsagot/Documents/tarotlogexpert/lib/node_modules/mquery/node_modules/sliced'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yogsagot/.npm/_logs/2018-04-18T18_21_36_524Z-debug.log

**Comment by vkarpov15** [comment]
We haven't published any releases recently and our CI passes, so we can't reproduce. Try doing `rm -rf node_modules && npm install`, that usually clears things up
